- name: Ensure required directories exist
  file:
    path: '{{ item }}'
    owner: '{{ ansible_real_user_id | int }}'
    group: '{{ ansible_real_group_id | int }}'
    state: directory
  with_items:
    - '{{ helper.web_cluster_dir }}'
  become: True

- name: Copy ignition files to the webserver html directory
  copy:
    src: '{{ helper.install_ignition_dir }}/{{ item.hostname }}.ign'
    dest: '{{ helper.web_cluster_dir }}/{{ item.hostname }}.ign'
    remote_src: True
    backup: True
  with_items: '{{ openshift_cluster_hosts }}'

- name: Download CoreOS image for bare metal
  get_url:
    url: '{{ item }}'
    dest: '{{ helper.web_cluster_dir }}/{{ item | basename }}'
    checksum: '{{ coreos.checksum }}'
  with_items:
    - '{{ coreos.installer_initramfs_url }}'
    - '{{ coreos.installer_kernel_url }}'
    - '{{ coreos.metal_bios_url }}'

- name: Ensure required directories exist
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ helper.tftp_dir }}'
  become: True

- name: Ensure required directories exist
  file:
    path: '{{ item }}'
    owner: '{{ ansible_real_user_id | int }}'
    group: '{{ ansible_real_group_id | int }}'
    state: directory
  with_items:
    - '{{ helper.tftp_cluster_dir }}'
  become: True

- name: Create {{ helper.tftp_cluster_dir }}/pxelinux.cfg directory
  file:
    dest: '{{ helper.tftp_cluster_dir }}/pxelinux.cfg'
    state: directory

- name: Create pxelinux.cfg configs
  template:
    src: files/boot/pxe/pxelinux.cfg/menu.cfg
    dest: '{{ helper.tftp_cluster_dir }}/pxelinux.cfg/01-{{ item.macaddr | regex_replace(":", "-") }}'
  with_items: '{{ openshift_cluster_hosts }}'
